// One-shot climate recalibration: re-anchors the `climate` sub-factor of every
// assessment to authoritative climate science (ND-GAIN vulnerability+readiness,
// Germanwatch CRI, World Bank CCDR, IPCC AR6, sea-level data) and the
// temperature-GDP/latitude literature (credits high-latitude net beneficiaries).
// Only the climate sub-factor is touched; weight is preserved. Run via:
//   node scripts/apply-climate.mjs && node scripts/compute-scores.mjs && node scripts/build-index.mjs
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

// iso3 -> [near, long, confidence, note]
const CLIMATE = {
  // ── Africa ──
  DZA: [-4, -5, 0.7, "Severe water stress, extreme heat, Saharan aridity, but oil-funded readiness above the Sahel. (ND-GAIN; WB MENA)"],
  AGO: [-5, -6, 0.66, "High vulnerability/low readiness; recurrent severe southern drought plus coastal flood/erosion. (ND-GAIN; WB)"],
  BEN: [-5, -6, 0.65, "Coastal erosion on a low Gulf-of-Guinea shore, flooding, rain-fed farming, weak readiness. (ND-GAIN; IPCC AR6)"],
  BWA: [-4, -5, 0.68, "Acute Kalahari aridity/heat and severe water scarcity, with better governance/readiness than peers. (ND-GAIN; WB)"],
  BFA: [-7, -8, 0.72, "Among the world's most vulnerable (ND-GAIN bottom-15) - Sahelian drought, desertification, heat, conflict-degraded readiness. (ND-GAIN)"],
  BDI: [-6, -7, 0.66, "ND-GAIN bottom-20 - landslides, floods, erratic rains on dense subsistence hills, near-zero adaptive capacity. (ND-GAIN; WB)"],
  CPV: [-4, -6, 0.6, "A Sahelian-Atlantic island state - chronic drought/water scarcity plus sea-level/coastal exposure, with relatively higher SIDS readiness. (ND-GAIN; IPCC)"],
  CMR: [-5, -6, 0.64, "Split far-north Sahel drought vs flood-prone south, Lake Chad shrinkage, weak readiness. (ND-GAIN; WB)"],
  CAF: [-7, -8, 0.68, "Among the most vulnerable globally (ND-GAIN bottom-10) - conflict has collapsed adaptive capacity. (ND-GAIN)"],
  TCD: [-7, -8, 0.74, "ND-GAIN bottom-5 - severe Sahel drought, desertification, Lake Chad collapse, recurrent flood, least-prepared. (ND-GAIN; WB)"],
  COM: [-6, -8, 0.6, "An Indian-Ocean SIDS - cyclones, coastal/sea-level exposure, freshwater scarcity, very low readiness. (ND-GAIN; IPCC SIDS)"],
  COG: [-5, -6, 0.6, "Coastal flood/erosion on a low Atlantic shore, with oil-dependent low readiness. (ND-GAIN; WB)"],
  COD: [-6, -7, 0.66, "ND-GAIN bottom-20 - vast floods, erratic rains, conflict-shattered readiness despite the Congo-basin resource base. (ND-GAIN)"],
  CIV: [-4, -5, 0.64, "Coastal erosion/flood on a low shore, with relatively stronger economy/readiness for the region. (ND-GAIN; WB)"],
  DJI: [-6, -7, 0.66, "Extreme heat, chronic drought, near-total food-import dependence, water scarcity, coastal exposure. (ND-GAIN; WB Horn)"],
  EGY: [-5, -7, 0.72, "An acute Nile-Delta sea-level/saline-intrusion threat plus extreme heat/water scarcity - exposure existential by 2050. (ND-GAIN; IPCC AR6)"],
  GNQ: [-5, -6, 0.55, "A low-readiness oil state with coastal-flood exposure and weak adaptive institutions despite income. (ND-GAIN; WB)"],
  ERI: [-6, -7, 0.62, "ND-GAIN bottom band - Horn drought, extreme heat, desertification, near-zero readiness under isolation. (ND-GAIN)"],
  SWZ: [-5, -6, 0.62, "Recurrent severe drought, heat, and rain-fed agriculture, with limited adaptive capacity. (ND-GAIN; WB)"],
  ETH: [-6, -7, 0.7, "ND-GAIN bottom-25 - recurrent Horn drought plus deadly floods, a vast rain-fed population, low readiness. (ND-GAIN; WB)"],
  GAB: [-3, -4, 0.6, "~88% forest cover buffers and low population pressure, against coastal-flood exposure and oil-dependent readiness. (ND-GAIN; WB)"],
  GMB: [-6, -8, 0.64, "A low-lying Atlantic delta state - acute sea-level/saline-intrusion plus coastal erosion, tiny adaptive capacity. (ND-GAIN; IPCC)"],
  GHA: [-4, -5, 0.66, "Coastal erosion (Keta/Volta) and northern drought, with relatively better governance/readiness. (ND-GAIN; WB CCDR)"],
  GIN: [-5, -6, 0.6, "Heavy-rainfall flooding, coastal exposure, mining-degraded land, weak readiness. (ND-GAIN; WB)"],
  GNB: [-6, -8, 0.6, "A low-lying mangrove/coastal state - severe sea-level/erosion plus saline rice-paddy intrusion, near-zero readiness. (ND-GAIN; IPCC)"],
  KEN: [-5, -5, 0.78, "Horn drought plus deadly 2024 floods on a rain-dependent agriculture, with relatively better regional readiness. (ND-GAIN; WB)"],
  LSO: [-5, -6, 0.62, "Highland drought, soil erosion, and erratic rains on a rain-fed/herding economy, low readiness. (ND-GAIN; WB)"],
  LBR: [-5, -6, 0.6, "ND-GAIN bottom-30 - intense-rainfall flooding, coastal erosion on the Monrovia shore, post-war low readiness. (ND-GAIN; WB)"],
  LBY: [-5, -6, 0.62, "Extreme aridity/heat plus Derna-2023-style flash-flood risk, with conflict-collapsed adaptive governance despite oil. (ND-GAIN; Germanwatch CRI)"],
  MDG: [-6, -7, 0.72, "Among the world's most cyclone-exposed - recurrent cyclones plus a southern near-famine drought, consistently high Germanwatch CRI, low readiness. (Germanwatch CRI; ND-GAIN)"],
  MWI: [-6, -7, 0.7, "ND-GAIN bottom-25 - Cyclone Freddy 2023 devastation, drought-flood whiplash, rain-fed maize, very low readiness. (ND-GAIN; Germanwatch CRI)"],
  MLI: [-7, -8, 0.72, "ND-GAIN bottom-10 - Sahel drought, desertification, extreme heat, conflict-eroded readiness. (ND-GAIN)"],
  MRT: [-6, -7, 0.68, "Saharan/Sahel drought, desertification, sandstorms, and low-lying Nouakchott coastal/sea-level risk. (ND-GAIN; WB)"],
  MUS: [-2, -4, 0.66, "An Indian-Ocean SIDS with cyclone plus sea-level exposure, but by far the highest African adaptive readiness (top-half ND-GAIN). (ND-GAIN; IPCC SIDS)"],
  MAR: [-4, -5, 0.72, "Severe multi-year drought, water stress, and heat, but among Africa's stronger readiness/adaptation programs. (ND-GAIN; WB MENA)"],
  MOZ: [-7, -8, 0.74, "Top-tier Germanwatch CRI (Idai/Kenneth/Freddy) - cyclones plus coastal sea-level plus flood-drought, very low readiness. (Germanwatch CRI; ND-GAIN)"],
  NAM: [-4, -5, 0.66, "Extreme aridity (the driest in sub-Saharan Africa) and recurrent drought, with better governance/readiness offsets. (ND-GAIN; WB)"],
  NER: [-8, -9, 0.74, "Near ND-GAIN rock-bottom - extreme Sahel desertification/heat/drought, the fastest population growth, near-zero readiness. (ND-GAIN)"],
  NGA: [-5, -6, 0.68, "Lagos/delta coastal-flood plus sea-level, northern desertification, a vast exposed population, weak readiness. (ND-GAIN; WB CCDR)"],
  RWA: [-4, -5, 0.66, "Landslides/floods on steep terrain, but notably strong governance/readiness for the region. (ND-GAIN; WB)"],
  STP: [-5, -7, 0.55, "An equatorial-Atlantic SIDS - coastal/sea-level erosion plus freshwater and rainfall shifts, tiny adaptive capacity. (ND-GAIN; IPCC SIDS)"],
  SEN: [-5, -6, 0.66, "Sahel drought plus low-lying Dakar/Saint-Louis coastal erosion and sea-level, moderate readiness. (ND-GAIN; IPCC AR6)"],
  SYC: [-3, -5, 0.62, "An Indian-Ocean SIDS with sea-level/reef/coastal exposure, but the highest-income African state with relatively strong readiness. (ND-GAIN; IPCC SIDS)"],
  SLE: [-6, -7, 0.64, "ND-GAIN bottom-25 - intense-rain flooding/landslides (2017 Freetown), coastal erosion, very low readiness. (ND-GAIN; WB)"],
  SOM: [-8, -9, 0.72, "Near ND-GAIN rock-bottom - chronic drought-famine plus flash floods and locusts, state collapse = near-zero readiness. (ND-GAIN; WB Horn)"],
  ZAF: [-3, -4, 0.72, "The highest-readiness state in sub-Saharan Africa - severe drought (Cape Town 'Day Zero')/water stress, but real adaptive capacity. (ND-GAIN; WB CCDR)"],
  SSD: [-8, -9, 0.72, "ND-GAIN dead-last band - catastrophic recurrent flooding plus drought, conflict, near-total absence of adaptive capacity. (ND-GAIN; WB)"],
  SDN: [-7, -8, 0.7, "ND-GAIN bottom band - Sahel drought, extreme heat, Nile/flash flooding, war-collapsed readiness. (ND-GAIN)"],
  TZA: [-5, -5, 0.66, "Drought-flood swings, coastal/Zanzibar sea-level exposure, rain-fed agriculture, modest readiness. (ND-GAIN; WB)"],
  TGO: [-5, -6, 0.62, "Coastal erosion on a very short low shore, northern drought, flooding, weak readiness. (ND-GAIN; WB)"],
  TUN: [-4, -5, 0.68, "Water scarcity, drought, heat, and coastal erosion, but relatively higher readiness than the Sahel. (ND-GAIN; WB MENA)"],
  UGA: [-5, -6, 0.66, "Landslides, drought-flood whiplash, Lake Victoria variability, a rain-fed economy, weak readiness. (ND-GAIN; WB)"],
  ZMB: [-5, -6, 0.68, "The severe 2023-24 drought crippled hydropower/agriculture (the energy-climate nexus), low readiness. (ND-GAIN; WB)"],
  ZWE: [-6, -7, 0.68, "Recurrent drought (incl. Cyclone Idai flooding), governance-eroded readiness, rain-fed/hydropower stress. (ND-GAIN; WB)"],
  // ── Asia / Middle East / Central Asia ──
  AFG: [-5, -7, 0.85, "ND-GAIN bottom-decile vulnerability plus near-zero readiness - drought, glacier-fed water decline, flash floods. (ND-GAIN; WB CCDR)"],
  ARM: [-3, -4, 0.7, "Mid-low vulnerability, moderate readiness - warming, water stress, agricultural exposure in the landlocked South Caucasus. (ND-GAIN; IPCC AR6)"],
  AZE: [-3, -4, 0.7, "Caspian level decline, heat and drought, water stress, with an oil-revenue buffer and middling readiness. (WB CCDR; IPCC AR6)"],
  BHR: [-3, -6, 0.8, "A tiny low-lying Gulf state - extreme wet-bulb heat by mid-century and sea-level/coastal squeeze, partly offset by wealth/AC. (IPCC AR6; WB)"],
  BGD: [-7, -9, 0.9, "A top global delta vulnerability - cyclones, sea-level rise, salinity, flooding; high ND-GAIN vulnerability, weak readiness. (ND-GAIN; IPCC AR6)"],
  BTN: [-2, -4, 0.7, "Carbon-negative but acute glacial-lake-outburst-flood and monsoon-landslide risk in a fragile Himalaya, low adaptive capacity. (IPCC AR6; WB)"],
  BRN: [-1, -3, 0.65, "Wealthy, forested, low-population, with rising coastal/heat exposure but a strong fiscal buffer. (ND-GAIN; IPCC AR6)"],
  KHM: [-5, -6, 0.8, "High vulnerability, low readiness - Mekong-flow disruption, flood/drought, Tonle Sap stress. (ND-GAIN; IPCC AR6)"],
  CHN: [-3, -4, 0.8, "Huge exposure (northern water scarcity, coastal-megacity/delta flooding, heat) offset by top-tier adaptive capacity. (IPCC AR6; WB CCDR)"],
  GEO: [-2, -3, 0.7, "Moderate vulnerability, decent readiness - Black Sea coast, mountain hazards, Caucasus heat/drought. (ND-GAIN; IPCC AR6)"],
  IND: [-5, -7, 0.85, "Severe heatwaves/wet-bulb in the north plains, monsoon variability, water stress, coastal flooding; large but uneven adaptive capacity. (IPCC AR6; ND-GAIN)"],
  IDN: [-4, -6, 0.8, "A vast archipelago - sea-level rise (sinking Jakarta), coastal/delta exposure, heat; improving but limited readiness. (WB CCDR; IPCC AR6)"],
  IRN: [-5, -7, 0.8, "An acute water crisis, drought, extreme heat, dust storms, and lake/aquifer collapse, with weak readiness under sanctions. (IPCC AR6; WB)"],
  IRQ: [-6, -8, 0.85, "Among the most climate-exposed Arab states - extreme heat, upstream-dam water scarcity, dust storms, salinity; very low readiness. (WB CCDR; IPCC AR6)"],
  ISR: [-2, -3, 0.75, "High readiness (desal, water tech) buffers Eastern-Med warming, drought, and heatwaves, with persistent coastal/aridification pressure. (IPCC AR6; ND-GAIN)"],
  JPN: [-2, -3, 0.8, "Resilient/high-capacity but with real exposure - intensifying typhoons, extreme heat, sea-level on dense coasts. (IPCC AR6; ND-GAIN)"],
  JOR: [-4, -6, 0.8, "One of the world's most water-scarce states - intensifying drought/heat, refugee-amplified demand, moderate readiness. (WB CCDR; IPCC AR6)"],
  KAZ: [-3, -4, 0.7, "Aridification, Aral/Balkhash water decline, heat and extreme cold, agricultural exposure; oil-funded but middling readiness. (IPCC AR6; ND-GAIN)"],
  KWT: [-4, -7, 0.8, "Among the hottest inhabited places - near-unliveable wet-bulb heat by mid-century, dust, desal-dependent water, with extreme wealth/AC offset. (IPCC AR6; WB)"],
  KGZ: [-4, -6, 0.8, "Glacier melt threatening regional water security, plus GLOF and landslide risk, low readiness. (IPCC AR6 cryosphere; WB CCDR)"],
  LAO: [-4, -6, 0.78, "High vulnerability, low readiness - Mekong dependence/disruption, flood/drought, landslides. (ND-GAIN; IPCC AR6)"],
  LBN: [-4, -5, 0.7, "Eastern-Med drought/heat, water stress, snowpack decline, with readiness gutted by state collapse and fiscal crisis. (IPCC AR6; ND-GAIN)"],
  MYS: [-2, -4, 0.75, "Moderate vulnerability, decent readiness - coastal flooding, sea-level, heat, peatland/forest exposure. (ND-GAIN; IPCC AR6)"],
  MDV: [-7, -9, 0.9, "Existential - the lowest-lying nation on Earth; sea-level rise threatens habitability despite adaptation spend. (IPCC AR6; ND-GAIN)"],
  MNG: [-5, -6, 0.8, "Rapid warming (>2x global), desertification, dzud (extreme winters) collapsing pastoralism, water decline, low readiness. (IPCC AR6; WB CCDR)"],
  MMR: [-6, -7, 0.85, "Consistently top of the Germanwatch CRI - cyclones, delta flooding, Ayeyarwady sea-level, conflict-shattered readiness. (Germanwatch CRI; ND-GAIN)"],
  NPL: [-4, -6, 0.8, "Glacier retreat, GLOF risk, monsoon flood/landslide, water-cycle disruption, low adaptive capacity. (IPCC AR6 cryosphere; WB CCDR)"],
  PRK: [-5, -6, 0.7, "High vulnerability, very low readiness - flood/drought-driven food insecurity, deforestation, an isolated economy. (ND-GAIN; WB)"],
  OMN: [-4, -7, 0.8, "Extreme heat, intensifying Arabian-Sea cyclones, water scarcity, near-unliveable wet-bulb risk offset by wealth/AC. (IPCC AR6; WB)"],
  PAK: [-6, -8, 0.88, "Catastrophic flood capacity (2022), extreme heat, glacier/Indus dependence, low readiness; recurrent Germanwatch CRI top-tier. (Germanwatch CRI; IPCC AR6)"],
  PHL: [-6, -7, 0.85, "Among the most disaster-exposed on Earth - frequent intense typhoons, storm surge, sea-level, moderate-low readiness. (Germanwatch CRI; WB CCDR)"],
  QAT: [-4, -7, 0.8, "Extreme/near-unliveable wet-bulb heat by mid-century, desal-dependent water, coastal exposure, with very high wealth/AC offset. (IPCC AR6; WB)"],
  SAU: [-4, -7, 0.8, "Extreme heat (Hajj wet-bulb risk), desert water scarcity, desal dependence, with a wealth/readiness partial offset. (IPCC AR6; WB CCDR)"],
  SGP: [-2, -3, 0.8, "Resilient/very high readiness, but equatorial heat-humidity and sea-level rise on a low-lying island-state are structural. (IPCC AR6; ND-GAIN)"],
  KOR: [-2, -3, 0.8, "High-capacity and resilient - intensifying heat, typhoons, and coastal flooding keep it modestly negative. (IPCC AR6; ND-GAIN)"],
  LKA: [-4, -5, 0.78, "Island monsoon variability, flood/drought/landslide, coastal/sea-level exposure, with readiness strained by fiscal crisis. (ND-GAIN; IPCC AR6)"],
  SYR: [-5, -7, 0.78, "Severe drought (a conflict trigger), water scarcity, extreme heat, with readiness destroyed by war. (IPCC AR6; WB)"],
  TJK: [-5, -7, 0.82, "A Central Asia water tower - rapid glacier loss threatens regional water; GLOF, flood, low readiness, the poorest in the region. (IPCC AR6 cryosphere; WB CCDR)"],
  THA: [-3, -5, 0.78, "Bangkok delta subsidence/sea-level, flooding (2011), drought, coastal exposure, moderate readiness. (WB CCDR; IPCC AR6)"],
  TLS: [-5, -6, 0.72, "High vulnerability, very low readiness - rainfall variability, food insecurity, coastal/landslide on a poor half-island. (ND-GAIN; IPCC AR6)"],
  TUR: [-3, -4, 0.75, "Mediterranean drought/heat intensification, water stress, wildfire, with relatively high adaptive capacity. (IPCC AR6; ND-GAIN)"],
  TKM: [-5, -7, 0.78, "Extreme desert heat, acute water scarcity (Amu Darya/Aral), aridification, very low readiness and opaque governance. (IPCC AR6; WB)"],
  ARE: [-3, -6, 0.8, "Extreme wet-bulb heat by mid-century, desal-dependent water, coastal/sea-level, with the highest-readiness Gulf offset near-term. (IPCC AR6; ND-GAIN)"],
  UZB: [-5, -7, 0.82, "The Aral Sea catastrophe, acute water scarcity, extreme heat, dust/salinity; upstream-dependent, low readiness. (WB CCDR; IPCC AR6)"],
  VNM: [-6, -8, 0.88, "The Mekong and Red River deltas - sea-level rise, salinity, subsidence, typhoons; a top global delta vulnerability, improving readiness. (IPCC AR6; WB CCDR)"],
  YEM: [-7, -8, 0.85, "Acute water depletion, extreme heat, flood, with readiness collapsed by war/famine - near-existential adaptive failure. (WB; IPCC AR6; ND-GAIN)"],
  // ── Europe ──
  ALB: [-3, -5, 0.7, "Mediterranean heat/drought/wildfire, mid-tier vulnerability and low readiness; an EEA Southern-Europe water-stress hotspot worsening by 2050. (ND-GAIN; EEA)"],
  AND: [0, -1, 0.55, "A high-Pyrenees state - alpine snowpack/tourism loss but altitude buffers heat; small, wealthy, adaptive. (IPCC AR6 mountains; EEA)"],
  AUT: [0, -1, 0.7, "Temperate, high readiness, but Alpine glacier/snow loss, rockfall, and 2024-type flooding. (ND-GAIN; IPCC AR6 mountains)"],
  BLR: [2, 3, 0.6, "Mid/high-latitude continental - longer growing seasons and milder winters net-positive, capped by lower readiness and drought variability. (Burke et al.; IPCC AR6)"],
  BEL: [1, 0, 0.7, "Low-vulnerability temperate, top readiness, but North-Sea coastal/urban flooding (2021 floods); an AMOC-slowdown tail caveat. (ND-GAIN; EEA; IPCC AR6 AMOC)"],
  BIH: [-3, -4, 0.6, "Balkan warming with drought, wildfire, and flood swings, with low adaptive readiness. (ND-GAIN; WB Western Balkans CCDR)"],
  BGR: [-3, -5, 0.7, "SE-Europe heat/drought and Black-Sea/agro water stress, the lowest-readiness EU member, markedly worse by mid-century. (ND-GAIN; EEA)"],
  HRV: [-3, -5, 0.7, "Mediterranean (Dalmatia) heat, drought, wildfire, and sea-level/coastal stress. (EEA; IPCC AR6 Mediterranean)"],
  CYP: [-5, -7, 0.8, "An Eastern-Med hotspot - among the fastest-warming, severe drought/water scarcity, and extreme heat approaching critical. (IPCC AR6; EEA)"],
  CZE: [1, 0, 0.7, "Temperate, high readiness, but recurrent drought (Elbe basin) and 2024 floods. (ND-GAIN; EEA)"],
  DNK: [4, 5, 0.75, "A high-latitude net beneficiary - top-tier readiness, milder winters/longer seasons; coastal/sea-level and AMOC-slowdown the caveats. (ND-GAIN; Burke et al.; IPCC AMOC)"],
  EST: [4, 6, 0.7, "A Baltic high-latitude winner - warming lengthens the growing season, milder winters, strong readiness; AMOC/Baltic-variability caveat. (ND-GAIN; Burke et al.)"],
  FIN: [5, 6, 0.75, "Among the clearest net beneficiaries - far-northern, top readiness, agricultural/forestry and winter upside; capped for transition volatility. (ND-GAIN; IPCC AR6; Burke et al.)"],
  FRA: [0, -2, 0.72, "Two-faced - temperate/high-readiness north vs Mediterranean-south heat/drought/wildfire and nuclear river-cooling stress; net long down. (ND-GAIN; EEA)"],
  DEU: [0, -2, 0.72, "Low-vulnerability, high-readiness, but rising heat, drought, and 2021-Ahr-type flooding. (ND-GAIN; EEA/UBA)"],
  GRC: [-4, -6, 0.78, "A Mediterranean front line - extreme heat, chronic drought, and catastrophic wildfire (2023/24), lower readiness. (IPCC AR6; Germanwatch CRI; EEA)"],
  HUN: [-1, -3, 0.68, "Pannonian-basin heat and intensifying drought on key agriculture, moderate readiness. (ND-GAIN; EEA)"],
  ISL: [5, 6, 0.7, "A high-latitude/sub-Arctic beneficiary - milder climate, geothermal-rich, very high readiness; localized glacier-melt/ocean-acidification and fisheries-shift risk. (ND-GAIN; IPCC AR6)"],
  IRL: [2, 1, 0.65, "Mild maritime, high readiness, low heat exposure - but the most AMOC-exposed state; a slowdown could sharply cool/destabilize NW Europe (flag the tail). (ND-GAIN; IPCC AMOC)"],
  ITA: [-3, -5, 0.75, "Mediterranean heat/drought (Po basin), wildfire, alpine glacier loss, and sea-level (Venice); high-readiness north, exposed south. (EEA; IPCC AR6)"],
  LVA: [4, 6, 0.7, "A Baltic high-latitude winner - longer growing season, milder winters, strong readiness; AMOC/coastal caveat. (ND-GAIN; Burke et al.)"],
  LIE: [0, -1, 0.55, "An Alpine micro-state - very high adaptive capacity but glacier/snow and Rhine-flood exposure. (IPCC AR6 mountains; EEA)"],
  LTU: [4, 6, 0.7, "A Baltic high-latitude beneficiary - warming-driven agricultural/season upside, good readiness; AMOC/Baltic caveat. (ND-GAIN; Burke et al.)"],
  LUX: [1, 0, 0.65, "Wealthy, top-readiness temperate, with modest heat and Moselle/river-flood exposure; an AMOC tail caveat. (ND-GAIN; EEA)"],
  MLT: [-5, -7, 0.78, "A Central-Med island - severe water scarcity, extreme heat, sea-level, and no freshwater buffer; high income aids adaptation but physical limits bite. (IPCC AR6; EEA)"],
  MDA: [-2, -4, 0.6, "An SE-Europe agrarian economy hit by intensifying drought/heat on rain-fed farming, with low readiness/resources. (ND-GAIN; WB CCDR)"],
  MCO: [-2, -4, 0.55, "A Mediterranean coastal city-state - extreme wealth/adaptation but heat, marine heatwaves, and sea-level on a tiny footprint. (IPCC AR6; EEA)"],
  MNE: [-3, -4, 0.6, "Adriatic/Balkan heat, drought, wildfire, and coastal stress, with low readiness. (ND-GAIN; EEA)"],
  NLD: [1, -1, 0.7, "Best-in-world flood engineering and top readiness offset extreme sea-level/subsidence near-term; AMOC-slowdown plus accelerating SLR are the long-term tail. (ND-GAIN; IPCC AMOC/SLR)"],
  MKD: [-3, -5, 0.62, "Southern-Balkan heat, drought, and wildfire on exposed agriculture, low readiness. (ND-GAIN; EEA)"],
  NOR: [4, 5, 0.75, "A high-latitude net beneficiary - top readiness, hydro-rich, milder winters, Arctic/Northern-Sea-Route access; localized flood/landslide and AMOC tail caveat. (ND-GAIN; IPCC AR6; Burke et al.)"],
  POL: [1, 0, 0.68, "Temperate, improving readiness, but Baltic-coast flooding, drought, and a coal-heavy transition. (ND-GAIN; EEA)"],
  PRT: [-4, -6, 0.76, "Iberian heat, severe drought/desertification (south), and major wildfire, lower readiness than core EU. (IPCC AR6; EEA; Germanwatch CRI)"],
  ROU: [-2, -4, 0.65, "SE-Europe heat and intensifying drought on large rain-fed agriculture, plus Danube flood swings, moderate readiness. (ND-GAIN; EEA)"],
  RUS: [2, 1, 0.5, "Two-sided - high-latitude agricultural and Arctic/Northern-Sea-Route upside, but permafrost-thaw infrastructure collapse, Siberian wildfire, and methane feedbacks plus weak readiness; mildly positive near, genuinely uncertain long. (IPCC AR6; ND-GAIN; Burke et al.)"],
  SMR: [-2, -4, 0.5, "Enclaved in central Italy - Mediterranean/Apennine heat, drought, and wildfire exposure, with high income aiding adaptation. (IPCC AR6; EEA)"],
  SRB: [-2, -4, 0.62, "Balkan/Pannonian heat and drought on agriculture, plus river flooding, low-moderate readiness. (ND-GAIN; EEA)"],
  SVK: [1, 0, 0.65, "Temperate Central-European with good readiness, and Carpathian/Danube flood and drought exposure. (ND-GAIN; EEA)"],
  SVN: [-1, -3, 0.62, "Transitional - alpine north plus Adriatic/Mediterranean heat-drought-wildfire and severe 2023 flooding. (EEA; IPCC AR6)"],
  ESP: [-4, -6, 0.8, "Warming ~1.6x the global mean, structural water stress/desertification, extreme heat, and wildfire; high readiness cannot offset physical drying. (AEMET; IPCC AR6; EEA)"],
  SWE: [4, 6, 0.75, "A high-latitude net beneficiary - top readiness, longer growing seasons, milder winters, forestry upside; transition volatility and AMOC tail the caveats. (ND-GAIN; IPCC AR6; Burke et al.)"],
  CHE: [0, -2, 0.7, "The wealthiest adapter but with acute Alpine glacier collapse, rockfall, snow loss, and river-flood; long down despite top readiness. (ND-GAIN; IPCC AR6 mountains)"],
  UKR: [-1, -3, 0.55, "A major rain-fed breadbasket exposed to intensifying southern drought/heat; warming partly extends northern seasons but net negative, with war degrading readiness. (ND-GAIN; IPCC AR6)"],
  GBR: [2, 1, 0.65, "Mild maritime, high readiness, low heat exposure - but among the most AMOC-exposed states; a slowdown could sharply cool/wet NW Europe (flag the tail). (ND-GAIN; IPCC AMOC)"],
  // ── Americas ──
  ATG: [-6, -8, 0.8, "A high-vulnerability SIDS - Beryl-class hurricanes plus sea-level rise threaten Barbuda's low coast. (ND-GAIN; IPCC AR6 SIDS)"],
  ARG: [1, 0, 0.7, "Southern-cone temperate, moderate readiness - Pampas drought plus Andean melt offset the latitude upside. (WB CCDR)"],
  BHS: [-7, -9, 0.85, "A low-lying limestone archipelago (~80% of land <1m) - the Dorian/Beryl precedent plus sea-level rise is near-existential. (IPCC AR6 SLR)"],
  BRB: [-6, -8, 0.8, "High-readiness but acutely water-scarce SIDS - coral/coast loss plus hurricanes, worse with SLR. (Germanwatch CRI; IPCC)"],
  BLZ: [-5, -7, 0.75, "Low coastal cays plus reef dependence plus a dry-corridor edge, high vulnerability. (WB CCDR)"],
  BOL: [-5, -7, 0.75, "Andean glacier loss (La Paz/El Alto water) plus Amazon/Chiquitano drought-fire, high vulnerability, low readiness. (ND-GAIN)"],
  BRA: [-4, -6, 0.75, "Amazon dieback/tipping-point stress plus Northeast drought plus 2024 record fires/floods. (IPCC AR6; ND-GAIN)"],
  CAN: [4, 6, 0.7, "A net beneficiary - high-latitude agriculture plus Arctic access, very high readiness; the wildfire/permafrost caveat caps it. (Burke et al.; ND-GAIN)"],
  CHL: [0, -1, 0.7, "High readiness but a mega-drought plus water stress plus coastal exposure - near-neutral, slightly worse long. (WB CCDR)"],
  COL: [-4, -5, 0.7, "Andean water stress plus Caribbean/Pacific coast plus ENSO swings, moderate readiness. (ND-GAIN)"],
  CRI: [-3, -4, 0.7, "The best-prepared Central American state, but dual-coast storms plus dry-corridor exposure. (WB CCDR)"],
  CUB: [-6, -8, 0.75, "A large low-lying island - frequent major hurricanes plus saltwater intrusion plus low economic readiness. (IPCC AR6 SIDS)"],
  DMA: [-7, -9, 0.8, "2017 Maria wiped ~226% of GDP - a mountainous SIDS with extreme cyclone exposure. (Germanwatch CRI; IPCC AR6)"],
  DOM: [-5, -6, 0.7, "Hurricane belt plus coastal tourism plus Hispaniola drought, mid vulnerability with moderate readiness. (ND-GAIN)"],
  ECU: [-5, -6, 0.7, "Andean glacier/water loss plus strong-ENSO flooding plus Galapagos exposure, low readiness. (ND-GAIN)"],
  SLV: [-6, -8, 0.8, "A Central American Dry Corridor epicenter - chronic drought plus a tiny Pacific coast plus low readiness. (WB CCDR)"],
  GRD: [-7, -9, 0.8, "Devastated by 2004 Ivan; 2024 Beryl flattened Carriacou/Petite Martinique - a high-exposure SIDS. (IPCC AR6)"],
  GTM: [-6, -8, 0.8, "Dry-corridor drought plus dual-coast storms plus highland landslides, high vulnerability, low readiness. (ND-GAIN)"],
  GUY: [-6, -9, 0.8, "The capital plus ~90% of the population on a coast below sea level behind an aging seawall - severe SLR exposure. (WB CCDR)"],
  HTI: [-8, -9, 0.85, "The lowest-readiness state in the hemisphere - deforestation plus hurricanes plus drought plus collapsed governance. (ND-GAIN; IPCC AR6)"],
  HND: [-6, -8, 0.8, "The 1998 Mitch and Eta/Iota 2020 precedent - dry-corridor plus dual-coast plus low readiness. (Germanwatch CRI long-term top-10)"],
  JAM: [-6, -8, 0.85, "2025 Hurricane Melissa (Cat 5, ~41% of GDP) is the anchor - high SIDS exposure plus sea-level rise. (IPCC AR6)"],
  MEX: [-4, -5, 0.75, "Northern/SW water stress plus dual-coast hurricanes (Otis 2023) plus heat, decent but strained readiness. (WB CCDR)"],
  NIC: [-6, -8, 0.8, "Dry-corridor drought plus the Caribbean hurricane corridor (Eta/Iota) plus low readiness/governance. (ND-GAIN)"],
  PAN: [-4, -5, 0.75, "Canal drought (2023-24 draft restrictions) plus dual-coast plus watershed stress, relatively higher readiness. (WB CCDR)"],
  PRY: [-4, -5, 0.7, "Landlocked but extreme heat plus Parana drought (record-low river) plus Chaco deforestation, low readiness. (ND-GAIN)"],
  PER: [-5, -7, 0.75, "Tropical-glacier loss (the largest share globally) plus Lima water plus strong-ENSO flooding, low readiness. (IPCC AR6)"],
  KNA: [-6, -8, 0.8, "A small two-island SIDS - hurricane belt plus coastal/tourism dependence plus SLR. (IPCC AR6 SIDS)"],
  LCA: [-7, -8, 0.8, "A mountainous SIDS in the hurricane corridor (Beryl 2024) plus reef/coast loss, high CRI exposure. (Germanwatch CRI)"],
  VCT: [-7, -9, 0.8, "2024 Hurricane Beryl devastated Union Island/the Grenadines (~90% of structures damaged) - acute SIDS exposure. (IPCC AR6)"],
  SUR: [-6, -9, 0.8, "~87% of the population on a low coastal plain below/near sea level - severe SLR plus flooding. (WB CCDR)"],
  TTO: [-3, -5, 0.7, "A higher-income, lower-hurricane-frequency SIDS, but coastal/SLR plus ecosystem stress, with an oil economy limiting transition readiness. (ND-GAIN)"],
  USA: [-4, -5, 0.75, "SW water stress plus Gulf/Atlantic hurricanes plus Western wildfire plus FL/CA insurance-market failure; high but eroding adaptive capacity. (IPCC AR6 WGII NA)"],
  URY: [1, 0, 0.7, "Temperate, with the highest readiness in South America - drought plus coastal exposure cap the upside. (WB CCDR)"],
  VEN: [-6, -8, 0.8, "Andean glacier loss (the last glacier gone 2024) plus collapsed institutional readiness plus flood/landslide exposure. (ND-GAIN)"],
  // ── Oceania ──
  AUS: [-3, -5, 0.8, "Black Summer bushfires, Murray-Darling drought, and Great Barrier Reef mass-bleaching (5 events since 2016); wealthy/high-readiness but severe heat/fire exposure worsening. (IPCC AR6; ND-GAIN)"],
  FJI: [-5, -7, 0.78, "High cyclone/SLR exposure (TC Winston 2016, the costliest S. Hemisphere cyclone), moderate adaptive capacity, relocating coastal villages. (WB Pacific CCDR)"],
  KIR: [-7, -9, 0.85, "A low-lying atoll nation - freshwater-lens salinization and inundation threaten habitability; bought land in Fiji as contingency. (IPCC AR6; ND-GAIN)"],
  MHL: [-7, -9, 0.85, "An atoll nation ~2m elevation - Majuro chronic king-tide flooding, freshwater-lens loss, projected partial uninhabitability by ~2050. (WB; IPCC AR6)"],
  FSM: [-5, -7, 0.72, "Mixed high islands plus atolls - SLR/coastal-erosion and typhoon exposure, low adaptive capacity. (WB Pacific CCDR; IPCC AR6)"],
  NRU: [-5, -7, 0.7, "A raised-coral island (less SLR inundation) but a phosphate-mined, near-uninhabitable interior, water/heat stress, near-total import dependence. (IPCC AR6)"],
  NZL: [-1, -3, 0.78, "Temperate, resilient, high-readiness, but rising coastal-flood/managed-retreat costs and 2023 Cyclone Gabrielle signal worsening exposure. (IPCC AR6; ND-GAIN)"],
  PLW: [-4, -6, 0.7, "High islands aid resilience, but a reef-dependent economy, coral bleaching, SLR, and typhoon exposure. (WB Pacific CCDR)"],
  PNG: [-5, -7, 0.72, "Carteret Islanders among the first climate-displaced; highland landslides/floods, very low adaptive capacity, high disaster exposure. (IPCC AR6; WB CCDR)"],
  WSM: [-5, -7, 0.74, "Cyclone/SLR/coastal-erosion exposure (and the 2009 tsunami) concentrated on the low coastal strip where most live. (WB Pacific CCDR)"],
  SLB: [-6, -8, 0.76, "Has already lost >=5 reef islands to SLR (Nuatambu etc.), high cyclone/flood exposure, the lowest adaptive capacity in the region. (IPCC AR6)"],
  TON: [-6, -8, 0.78, "The 2022 Hunga Tonga eruption/tsunami plus TC Gita/Harold - extreme compound geohazard plus cyclone/SLR on low-lying populated islands. (IPCC AR6)"],
  TUV: [-8, -10, 0.88, "The world's most existentially SLR-threatened atoll nation (~2m max elevation), digitizing statehood, projected inundation this century. (IPCC AR6; ND-GAIN)"],
  VUT: [-6, -8, 0.82, "The WorldRiskIndex #1 disaster-risk country (TC Pam 2015, Harold, twin-2023 cyclones) - extreme cyclone/SLR/volcanic exposure, low adaptive capacity. (WorldRiskIndex)"],
};

const dir = "assessments";
let changed = 0, missing = [];
const codes = new Set(Object.keys(CLIMATE));
for (const f of readdirSync(dir).filter((f) => f.endsWith(".json"))) {
  const p = join(dir, f);
  const d = JSON.parse(readFileSync(p, "utf8"));
  const rec = CLIMATE[d.iso3];
  if (!rec) { missing.push(`${d.iso3} ${d.country}`); continue; }
  const [near, long, conf, note] = rec;
  const cl = d.categories.physical_practical.sub_factors.climate;
  const weight = cl.weight;
  let next;
  if (near === long) next = { score: near, weight, confidence: conf, notes: note };
  else next = { score_near: near, score_long: long, score: null, weight, confidence: conf, notes: note };
  d.categories.physical_practical.sub_factors.climate = next;
  writeFileSync(p, JSON.stringify(d, null, 2) + "\n");
  changed++;
  codes.delete(d.iso3);
}
console.log(`[apply-climate] updated ${changed} files`);
if (missing.length) console.log(`[apply-climate] no mapping for: ${missing.join(", ")}`);
if (codes.size) console.log(`[apply-climate] unused mapping codes: ${[...codes].join(", ")}`);
